"""v02

Revision ID: 112254dd3d49
Revises: cc3bc45aa367
Create Date: 2023-12-18 12:21:44.266676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '112254dd3d49'
down_revision: Union[str, None] = 'cc3bc45aa367'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_social', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_social')
    # ### end Alembic commands ###
