"""V0_5

Revision ID: 52e5833d9998
Revises: bbed47abfeb3
Create Date: 2023-12-21 17:04:33.767995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52e5833d9998'
down_revision: Union[str, None] = 'bbed47abfeb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers_followings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('followed_by', sa.Integer(), nullable=False),
    sa.Column('followed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['followed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_followers_followings_followed_by'), 'followers_followings', ['followed_by'], unique=False)
    op.create_index(op.f('ix_followers_followings_user_id'), 'followers_followings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_followers_followings_user_id'), table_name='followers_followings')
    op.drop_index(op.f('ix_followers_followings_followed_by'), table_name='followers_followings')
    op.drop_table('followers_followings')
    # ### end Alembic commands ###
