"""v0_9

Revision ID: 7c88bedc9186
Revises: b694e51127dd
Create Date: 2023-12-27 16:26:11.671660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c88bedc9186'
down_revision: Union[str, None] = 'b694e51127dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers_followings', sa.Column('followed_to', sa.Integer(), nullable=False))
    op.drop_index('ix_followers_followings_user_id', table_name='followers_followings')
    op.create_index(op.f('ix_followers_followings_followed_to'), 'followers_followings', ['followed_to'], unique=False)
    op.drop_constraint('followers_followings_user_id_fkey', 'followers_followings', type_='foreignkey')
    op.create_foreign_key(None, 'followers_followings', 'users', ['followed_to'], ['id'])
    op.drop_column('followers_followings', 'user_id')
    op.add_column('request_to_user', sa.Column('requested_to', sa.Integer(), nullable=False))
    op.drop_index('ix_request_to_user_user_id', table_name='request_to_user')
    op.create_index(op.f('ix_request_to_user_requested_to'), 'request_to_user', ['requested_to'], unique=False)
    op.drop_constraint('request_to_user_user_id_fkey', 'request_to_user', type_='foreignkey')
    op.create_foreign_key(None, 'request_to_user', 'users', ['requested_to'], ['id'])
    op.drop_column('request_to_user', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_to_user', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'request_to_user', type_='foreignkey')
    op.create_foreign_key('request_to_user_user_id_fkey', 'request_to_user', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_request_to_user_requested_to'), table_name='request_to_user')
    op.create_index('ix_request_to_user_user_id', 'request_to_user', ['user_id'], unique=False)
    op.drop_column('request_to_user', 'requested_to')
    op.add_column('followers_followings', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'followers_followings', type_='foreignkey')
    op.create_foreign_key('followers_followings_user_id_fkey', 'followers_followings', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_followers_followings_followed_to'), table_name='followers_followings')
    op.create_index('ix_followers_followings_user_id', 'followers_followings', ['user_id'], unique=False)
    op.drop_column('followers_followings', 'followed_to')
    # ### end Alembic commands ###
