"""v0_3

Revision ID: 7d351bf9b62c
Revises: a1e6c68877d8
Create Date: 2023-12-22 15:23:55.293854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d351bf9b62c'
down_revision: Union[str, None] = 'a1e6c68877d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_to_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('request_accepted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_to_user_requested_by'), 'request_to_user', ['requested_by'], unique=False)
    op.create_index(op.f('ix_request_to_user_user_id'), 'request_to_user', ['user_id'], unique=False)
    op.create_index(op.f('ix_comment_likes_comment_id'), 'comment_likes', ['comment_id'], unique=False)
    op.create_index(op.f('ix_comment_likes_reply_id'), 'comment_likes', ['reply_id'], unique=False)
    op.add_column('post_comments_reply', sa.Column('reply_like_count', sa.Integer(), nullable=True))
    op.add_column('post_likes', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.create_index(op.f('ix_post_likes_liked_by'), 'post_likes', ['liked_by'], unique=False)
    op.create_index(op.f('ix_post_likes_post_id'), 'post_likes', ['post_id'], unique=False)
    op.drop_column('post_likes', 'liked_at')
    op.add_column('posts', sa.Column('is_archive', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'is_archive')
    op.add_column('post_likes', sa.Column('liked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_post_likes_post_id'), table_name='post_likes')
    op.drop_index(op.f('ix_post_likes_liked_by'), table_name='post_likes')
    op.drop_column('post_likes', 'created_at')
    op.drop_column('post_comments_reply', 'reply_like_count')
    op.drop_index(op.f('ix_comment_likes_reply_id'), table_name='comment_likes')
    op.drop_index(op.f('ix_comment_likes_comment_id'), table_name='comment_likes')
    op.drop_index(op.f('ix_request_to_user_user_id'), table_name='request_to_user')
    op.drop_index(op.f('ix_request_to_user_requested_by'), table_name='request_to_user')
    op.drop_table('request_to_user')
    # ### end Alembic commands ###
