"""v0_2

Revision ID: a1e6c68877d8
Revises: 79de8bc67179
Create Date: 2023-12-22 11:44:50.222506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1e6c68877d8'
down_revision: Union[str, None] = '79de8bc67179'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_comments_reply',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comment_reply', sa.String(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['post_comments.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_comments_reply_comment_id'), 'post_comments_reply', ['comment_id'], unique=False)
    op.create_index(op.f('ix_post_comments_reply_post_id'), 'post_comments_reply', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_comments_reply_user_id'), 'post_comments_reply', ['user_id'], unique=False)
    op.add_column('comment_likes', sa.Column('reply_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment_likes', 'post_comments_reply', ['reply_id'], ['id'])
    op.drop_column('users', 'follower_count')
    op.drop_column('users', 'following_count')
    op.drop_column('users', 'post_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('post_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('following_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('follower_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comment_likes', type_='foreignkey')
    op.drop_column('comment_likes', 'reply_id')
    op.drop_index(op.f('ix_post_comments_reply_user_id'), table_name='post_comments_reply')
    op.drop_index(op.f('ix_post_comments_reply_post_id'), table_name='post_comments_reply')
    op.drop_index(op.f('ix_post_comments_reply_comment_id'), table_name='post_comments_reply')
    op.drop_table('post_comments_reply')
    # ### end Alembic commands ###
